title: לעכטיג
description: א היימיש-אידיש פלאטפארמע פאר התאחדות אנ"ש דארה"ב וקנדא

theme: minima
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      lang: yi
      header_pages:
  - index.md
  - pages/about.md
  - pages/help.md

